collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.0609319
color:
  saturation: 1
  brandStrength: 0.007168459
  lightness: 1
  brandColors:
    - '#130F0E'
    - '#FBF9FC'
    - '#1C3843'
    - '#696F6F'
    - '#A49A91'
  rhythmicContrast: 0.5412186
layout_spectrum: 0.6182796
name: INTO THE WORLD STORIES
