typography_spectrum: 0.0609319
color:
  saturation: 0.8387097
  brandStrength: 0.04659498
  lightness: 1
  brandColors:
    - '#130F0E'
    - '#FBF9FC'
    - '#1C3843'
    - '#696F6F'
    - '#A49A91'
  rhythmicContrast: 0.5089605
opengraph:
  type: video.movie
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/20012ee6-e2e3-4c86-904a-55ee184081c1.jpg
layout_spectrum: 0.8225806
analytics:
  google: UA-37252801-8
author:
  name: SO STUDIOS
  email: info@sostudiosfilm.com
  url: 'https://www.sostudiosfilm.com'
name: INTO THE WORLD STORIES
navigation:
  - name: ABOUT THE FILM
    id: 96057193-5915-4516-93e2-6a55754396e4
    type: content
  - name: 'SHARE YOUR #ITWSTORIES!'
    id: 1d6d3dfd-585f-44f5-98a5-d657455979a8
    type: content
  - name: OFFICIAL SITE
    url: 'https://www.sostudiosfilm.com/into-the-world'
    type: external
  - name: SO STUDIOS
    url: 'https://www.sostudiosfilm.com'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4cb19d8c-75b4-4dd1-8e04-bd554812d630.ico
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Find your own little world
