layout_spectrum: 0.5665263181712737
typography_spectrum: 0.9934243587293837
color:
  saturation: 0.999233787870219
  brandStrength: 0.56343575791714
  rhythmicContrast: 0.8905220201000166
  brandColors:
    - '#130F0E'
    - '#FBF9FC'
    - '#1C3843'
    - '#696F6F'
    - '#A49A91'
  lightness: 0.7834297705987597
opengraph:
  type: video.movie
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/20012ee6-e2e3-4c86-904a-55ee184081c1.jpg
analytics:
  google: UA-37252801-8
author:
  name: SO STUDIOS
  email: info@sostudiosfilm.com
  url: 'https://www.sostudiosfilm.com/'
name: INTO THE WORLD STORIES
navigation:
  - name: HOME
    url: 'http://itwstories.sostudiosfilm.com/'
    type: external
  - name: ABOUT THE FILM
    id: 96057193-5915-4516-93e2-6a55754396e4
    type: content
  - name: FEATURED STORIES
    id: 02981f28-2246-4346-9312-a927e2de147c
    type: content
  - name: 'SHARE YOUR #ITWSTORIES'
    id: 1d6d3dfd-585f-44f5-98a5-d657455979a8
    type: content
  - name: LINKS
    id: 46206462-e7f6-41dc-afa0-3b48b0ea6e51
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4cb19d8c-75b4-4dd1-8e04-bd554812d630.ico
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: ''
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/933ca4e8-d926-4eb1-9bcc-356f5a23e004.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/933ca4e8-d926-4eb1-9bcc-356f5a23e004.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/bd2b8c8e-a903-4390-a67b-41f0ac3fe620.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/bd2b8c8e-a903-4390-a67b-41f0ac3fe620.png
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: ''
purpose: []
logo: null
github: true
url: 'https://itwstories.com/'
