collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6200717
  brandStrength: 1
  lightness: 1
  brandColors:
    - '#11100E'
    - '#1D3A42'
    - '#FFFFFF'
    - '#636B6D'
    - '#A29990'
  rhythmicContrast: 0.6612903
typography_spectrum: 0.0609319
layout_spectrum: 0.8835126
name: INTO THE WORLD STORIES
