collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.3243728
  brandStrength: 0.4946237
  lightness: 1
  brandColors:
    - '#000000'
    - '#DBDBDB'
    - '#727272'
    - '#B2B2B2'
    - '#1D1D1D'
  rhythmicContrast: 0.2544803
typography_spectrum: 0.0609319
layout_spectrum: 0.6182796
name: INTO THE WORLD STORIES
