title: ''
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8387097
  brandStrength: 0.04659498
  rhythmicContrast: 0.5089605
  brandColors:
    - '#130F0E'
    - '#FBF9FC'
    - '#1C3843'
    - '#696F6F'
    - '#A49A91'
  lightness: 1
navigation:
  - url: 'https://www.sostudiosfilm.com/into-the-world'
    name: OFFICIAL SITE
    type: external
  - url: 'https://www.sostudiosfilm.com'
    name: SO STUDIOS
    type: external
analytics:
  google: UA-37252801-8
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/4cb19d8c-75b4-4dd1-8e04-bd554812d630.ico
name: INTO THE WORLD STORIES
author:
  name: SO STUDIOS
  email: info@sostudiosfilm.com
  url: 'https://www.sostudiosfilm.com'
opengraph:
  type: video.movie
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/20012ee6-e2e3-4c86-904a-55ee184081c1.jpg
typography_spectrum: 0.08243728
layout_spectrum: 0.4354839
